services:
  - type: web
    name: chenziviewload
    runtime: docker
    plan: free
    region: oregon
    dockerCommand: sh -c "cd frontend && npm install && npm run build && cd .. && npm install && node backend/src/app.js"
    startCommand: node backend/src/app.js
    branch: master
    healthCheckPath: /api/health
